#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####

sketchybar --bar height=37        \
                 position=top     \
                 sticky=off       \
                 padding_left=10  \
                 padding_right=10 \
                 color=$BAR_COLOR

##### Changing Defaults #####

sketchybar --default icon.font="SF Pro:Semibold:15.0"  \
                     icon.color=$TEXT                 \
                     label.font="SF Pro:Semibold:15.0" \
                     label.color=$TEXT                \
                     padding_left=5                    \
                     padding_right=5                   \
                     label.padding_left=4              \
                     label.padding_right=4             \
                     icon.padding_left=4               \
                     icon.padding_right=4 \
                     background.color=$ITEM_BG_COLOR       \
                     background.corner_radius=5            \
                     background.height=24                  \
                     label.padding_right=10                \
                     icon.padding_left=10                  \

##### Adding Mission Control Space Indicators #####

# -- Left Side Items --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# --- Right Side Items ---
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh


##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
