#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 3
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
type = "prompt"
alignment = "left"

[[blocks.segments]]
type = 'path'
style = "plain"
background = 'transparent'
foreground = '#cba6f7'
template = '{{ .Path }} ❯'

[blocks.segments.properties]
style = 'agnoster_short'
home_icon = "~"
folder_icon = " \ue5fe "

[[blocks.segments]]
type = "git"
style = "plain"
template = "{{ .HEAD }}"
background = "transparent"
foreground = "#f38ba8"

[blocks.segments.properties]
branch_icon = " \ue725 "
cherry_pick_icon = " \ue29b "
commit_icon = " \uf417 "
fetch_status = false
fetch_upstream_icon = false
merge_icon = " \ue727 "
no_commits_icon = " \uf0c3 "
rebase_icon = " \ue728 "
revert_icon = " \uf0e2 "
tag_icon = " \uf412 "


[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}magenta{{end}}",
]
background = 'transparent'
template = '❯'

[transient_prompt]
foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}magenta{{end}}",
]
background = 'transparent'
template = '❯ '

[secondary_prompt]
foreground = 'magenta'
background = 'transparent'
template = '❯❯ '
